FROM golang:1.24.3 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o agent cmd/agent/main.go

FROM alpine:latest
COPY --from=builder /app/agent /usr/local/bin/agent
CMD ["agent"]