apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-agent
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-agent
  template:
    metadata:
      labels:
        app: lb-agent
    spec:
      serviceAccountName: lb-agent
      containers:
      - name: lb-agent
        image: projectgreenist/kube-lb-agent:latest
        env:
        - name: WEBHOOK_URL
          value: "http://lb-webhook.basphere.local/vip"
        - name: CLUSTER_ID
          value: "consumer-cluster-2"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lb-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lb-agent
rules:
- apiGroups: [""]
  resources: ["services", "nodes"]
  verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lb-agent
subjects:
- kind: ServiceAccount
  name: lb-agent
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: lb-agent
  apiGroup: rbac.authorization.k8s.io
