apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loadbalancer-test
spec:
  selector:
    matchLabels:
      app: loadbalancer-test
  template:
    metadata:
      labels:
        app: loadbalancer-test
    spec:
      nodeSelector:
        app: worker
      containers:
      - name: loadbalancer-test
        image: projectgreenist/loadbalancer-test:latest
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP