apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-test
  labels:
    color: blue
spec:
  selector:
    app: loadbalancer-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local 
