---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lb-webhook
  namespace: kube-lb-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lb-webhook
rules:
- apiGroups: ["cilium.io"]
  resources: ["ciliumloadbalancerippools"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lb-webhook
subjects:
- kind: ServiceAccount
  name: lb-webhook
  namespace: kube-lb-services
roleRef:
  kind: ClusterRole
  name: lb-webhook
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lb-webhook
  namespace: kube-lb-services
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lb-webhook
  namespace: kube-lb-services
subjects:
- kind: ServiceAccount
  name: lb-webhook
  namespace: kube-lb-services
roleRef:
  kind: Role
  name: lb-webhook
  apiGroup: rbac.authorization.k8s.io